### ISSUE TITLE
SEA & Exchange Rate

### ISSUE THREAD

**Issue by petres** [bquast/wiod#1]
Hi,
it would be nice if you could also include the WIOD SEA (Socio Economic Accounts) as well as the exchange rates (http://www.wiod.org/protected3/data/update_sep12/EXR_WIOD_Sep12.xlsx).

Thanks!

**Comment by bquast** [comment]
Hi, that should be possible. Are you interesting in submitting a pull request?

**Comment by petres** [comment]
I don't know how to integrate it, also yearwise like the IO Tables, or better at one dataset?

**Comment by bquast** [comment]
We decided to do it year wise since the decompositions don't have any inherent time element. I think the same would apply here and it would also make sense to preseve a single approach to this question.

I would perhaps be a good idea to show how one could easily combine data across years after the decompositions in an example or vignette, I will look into this.

**Comment by bquast** [comment]
@vkummritz

**Comment by bquast** [comment]
This feature request does not relate to core functionality.
